### ISSUE TITLE
请问可以下载片花吗？

### ISSUE THREAD

**Issue by isping** [PyJun/Mooc_Downloader#12]
请问可以下载片花吗？

**Comment by CaecarGuo** [comment]
可以的，谢谢你wwヾ(๑╹◡╹)ﾉ"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"isping"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 上午10:36
收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PyJun/Mooc_Downloader] 请问可以下载片花吗？ (#12)




请问可以下载片花吗？

**Comment by isping** [comment]
> 可以的，谢谢你wwヾ(๑╹◡╹)ﾉ"
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"isping"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月16日(星期天) 上午10:36 收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[PyJun/Mooc_Downloader] 请问可以下载片花吗？ (#12) 请问可以下载片花吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

怎么下载呢？

> 可以的，谢谢你wwヾ(๑╹◡╹)ﾉ"
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"isping"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月16日(星期天) 上午10:36 收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[PyJun/Mooc_Downloader] 请问可以下载片花吗？ (#12) 请问可以下载片花吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
如何下载呢？

**Comment by CaecarGuo** [comment]
怎么样的都行，如果太麻烦你的话
就算了吧wwヾ(✿ﾟ▽ﾟ)ノ谢谢你


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"isping"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 上午10:42
收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送:&nbsp;" "<1399193948@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PyJun/Mooc_Downloader] 请问可以下载片花吗？ (#12)



 
可以的，谢谢你wwヾ(๑╹◡╹)ﾉ"
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"isping"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月16日(星期天) 上午10:36 收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[PyJun/Mooc_Downloader] 请问可以下载片花吗？ (#12) 请问可以下载片花吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
怎么下载呢？
  
可以的，谢谢你wwヾ(๑╹◡╹)ﾉ"
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"isping"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月16日(星期天) 上午10:36 收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[PyJun/Mooc_Downloader] 请问可以下载片花吗？ (#12) 请问可以下载片花吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
 如何下载呢？
