### ISSUE TITLE
现在学堂在线好像不能下载了

### ISSUE THREAD

**Issue by hqu-little-boy** [PyJun/Mooc_Downloader#18]

**Comment by PyJun** [comment]
会更新的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hqu-little-boy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 下午3:21
收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PyJun/Mooc_Downloader] 现在学堂在线好像不能下载了 (#18)

**Comment by hqu-little-boy** [comment]
> 会更新的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"hqu-little-boy"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月19日(星期四) 下午3:21 收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[PyJun/Mooc_Downloader] 现在学堂在线好像不能下载了 (#18) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

虽然很不好意思，但是这种反馈能要个vip吗？

**Comment by PyJun** [comment]
已经更新好了，最新版都没问题



---原始邮件---
发件人: "hqu-little-boy"<notifications@github.com&gt;
发送时间: 2020年4月5日(周日) 凌晨1:25
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "PyJun"<py.jun@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [PyJun/Mooc_Downloader] 现在学堂在线好像不能下载了 (#18)




  
会更新的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"hqu-little-boy"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月19日(星期四) 下午3:21 收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[PyJun/Mooc_Downloader] 现在学堂在线好像不能下载了 (#18) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
虽然很不好意思，但是这种反馈能要个vip吗？
